export const dummyContacts = [
  {
    id: 0,
    firstName: "Ronald",
    secondName: "Richards",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Wed 5, 2021",
  },
  {
    id: 1,
    firstName: "Jacob",
    secondName: "Jones",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Sun 15, 2021",
    profilePicUrl: "https://randomuser.me/api/portraits/med/men/51.jpg",
  },
  {
    id: 2,
    firstName: "Ronald",
    secondName: "Richards",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Wed 5, 2021",
  },
  {
    id: 3,
    firstName: "Jacob",
    secondName: "Jones",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Sun 15, 2021",
    profilePicUrl: "https://randomuser.me/api/portraits/med/men/51.jpg",
  },
  {
    id: 4,
    firstName: "Ronald",
    secondName: "Richards",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Wed 5, 2021",
  },
  {
    id: 5,
    firstName: "Jacob",
    secondName: "Jones",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Sun 15, 2021",
    profilePicUrl: "https://randomuser.me/api/portraits/med/men/51.jpg",
  },
  {
    id: 6,
    firstName: "Ronald",
    secondName: "Richards",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Wed 5, 2021",
  },
  {
    id: 7,
    firstName: "Jacob",
    secondName: "Jones",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Sun 15, 2021",
    profilePicUrl: "https://randomuser.me/api/portraits/med/men/51.jpg",
  },
  {
    id: 8,
    firstName: "Ronald",
    secondName: "Richards",
    role: "Owner",
    email: "albert@bower.com",
    createdAt: "Wed 5, 2021",
  },
];
