import React from "react";

import { MenuVertical } from "@bigbinary/neeto-icons";
import { Avatar, Dropdown } from "neetoui/v2";

export const columnData = setShowDeleteAlert => [
  {
    dataIndex: "first_name",
    key: "first_name",
    render: value => (
      <div className="flex items-center">
        <Avatar
          className="ml-2"
          user={{
            name: value,
          }}
        />
        <div className="ml-4">
          <h5>Ronald Richards</h5>
          <p>Owner</p>
        </div>
      </div>
    ),
    title: "First Name",
    width: 250,
  },
  {
    dataIndex: "email",
    key: "email",
    title: "Email",
    width: 50,
  },
  {
    dataIndex: "gender",
    key: "gender",
    title: "Gender",
    width: 150,
  },
  {
    dataIndex: "first_name",
    key: "first_name",
    render: () => (
      <div className="flex items-center">
        <Dropdown
          buttonStyle="link"
          icon={MenuVertical}
          onClose={function noRefCheck() {}}
          position="bottom-end"
        >
          <li>Edit</li>
          <li onClick={() => setShowDeleteAlert(true)}>Delete</li>
        </Dropdown>
      </div>
    ),
    width: 20,
  },
];

export const ROW_DATA = [
  {
    app_name: "Sub-Ex",
    app_version: "7.0.9",
    buzzword: "artificial intelligence",
    company_name: "Schuppe-Beier",
    credit_card_number: 3551746792304987,
    currency: "Ruble",
    currency_code: "RUB",
    department: "Training",
    domain_name: "freewebs.com",
    email: "brealy0@who.int",
    first_name: "Brennen",
    gender: "Male",
    guid: "cd75b6a6-54fa-4a0f-8fe9-5b62a461a2d0",
    id: 1,
    ip_address: "144.32.99.33",
    job_title: "Internal Auditor",
    key: 1,
    last_name: "Realy",
    shirt_size: "3XL",
  },
  {
    app_name: "Duobam",
    app_version: 4.92,
    buzzword: "Profit-focused",
    company_name: "Legros, Ankunding and Cartwright",
    credit_card_number: 3584141123636532,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Engineering",
    domain_name: "unc.edu",
    email: "mjaime1@jigsy.com",
    first_name: "Manny",
    gender: "Polygender",
    guid: "c48cfefc-9e04-4169-9b31-442b363c30e8",
    id: 2,
    ip_address: "41.191.104.169",
    job_title: "Community Outreach Specialist",
    key: 2,
    last_name: "Jaime",
    shirt_size: "M",
  },
  {
    app_name: "Asoka",
    app_version: 0.35,
    buzzword: "definition",
    company_name: "Hickle-Turcotte",
    credit_card_number: 4405563411056815,
    currency: "Euro",
    currency_code: "EUR",
    department: "Legal",
    domain_name: "businessinsider.com",
    email: "whuddlestone2@mapquest.com",
    first_name: "Wilton",
    gender: "Agender",
    guid: "894f0864-706d-4b76-b889-48ea99128687",
    id: 3,
    ip_address: "53.47.156.177",
    job_title: "Sales Associate",
    key: 3,
    last_name: "Huddlestone",
    shirt_size: "XL",
  },
  {
    app_name: "Zoolab",
    app_version: "0.3.5",
    buzzword: "next generation",
    company_name: "Jones Inc",
    credit_card_number: 3556557574431111,
    currency: "Dollar",
    currency_code: "USD",
    department: "Product Management",
    domain_name: "wordpress.com",
    email: "ctapply3@newsvine.com",
    first_name: "Crin",
    gender: "Polygender",
    guid: "c13fb646-6019-44c5-bc90-f53c992237fe",
    id: 4,
    ip_address: "44.224.117.201",
    job_title: "Tax Accountant",
    key: 4,
    last_name: "Tapply",
    shirt_size: "XL",
  },
  {
    app_name: "Wrapsafe",
    app_version: "0.1.4",
    buzzword: "Multi-tiered",
    company_name: "Moen, Kub and Beatty",
    credit_card_number: 5602218894989493000,
    currency: "Dram",
    currency_code: "AMD",
    department: "Marketing",
    domain_name: "adobe.com",
    email: "ashallow4@reference.com",
    first_name: "Antons",
    gender: "Non-binary",
    guid: "c8082a50-cbed-4107-8566-ae21eacc9c06",
    id: 5,
    ip_address: "106.27.145.38",
    job_title: "Quality Engineer",
    key: 5,
    last_name: "Shallow",
    shirt_size: "XL",
  },
  {
    app_name: "Tres-Zap",
    app_version: 1.4,
    buzzword: "Down-sized",
    company_name: "Hills Inc",
    credit_card_number: 3577689643877217,
    currency: "Peso",
    currency_code: "PHP",
    department: "Business Development",
    domain_name: "ed.gov",
    email: "jpeever5@mysql.com",
    first_name: "Junette",
    gender: "Agender",
    guid: "4a0081ee-cc8c-4e8d-a509-414f1e9bc82f",
    id: 6,
    ip_address: "107.200.153.250",
    job_title: "Civil Engineer",
    key: 6,
    last_name: "Peever",
    shirt_size: "M",
  },
  {
    app_name: "Fix San",
    app_version: 7.99,
    buzzword: "Reduced",
    company_name: "Douglas-Oberbrunner",
    credit_card_number: 3553225504871102,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Legal",
    domain_name: "edublogs.org",
    email: "jpalmby6@webs.com",
    first_name: "Julee",
    gender: "Polygender",
    guid: "0c92fac4-4c57-4882-89bd-05612ead4eaf",
    id: 7,
    ip_address: "166.202.115.161",
    job_title: "Structural Analysis Engineer",
    key: 7,
    last_name: "Palmby",
    shirt_size: "XL",
  },
  {
    app_name: "Lotlux",
    app_version: 4.7,
    buzzword: "orchestration",
    company_name: "Koepp LLC",
    credit_card_number: 3572576521356502,
    currency: "Real",
    currency_code: "BRL",
    department: "Legal",
    domain_name: "un.org",
    email: "itowe7@toplist.cz",
    first_name: "Izak",
    gender: "Bigender",
    guid: "4f5bcb5e-3c89-488b-9772-9b710b7c9b19",
    id: 8,
    ip_address: "103.225.165.252",
    job_title: "Tax Accountant",
    key: 8,
    last_name: "Towe",
    shirt_size: "S",
  },
  {
    app_name: "Latlux",
    app_version: 0.82,
    buzzword: "intranet",
    company_name: "Pagac, Spinka and Dooley",
    credit_card_number: 5602247062713142,
    currency: "Zloty",
    currency_code: "PLN",
    department: "Services",
    domain_name: "imdb.com",
    email: "bgosselin8@cornell.edu",
    first_name: "Blondy",
    gender: "Polygender",
    guid: "27701bfe-39ba-487c-90c7-9d1b7f05c001",
    id: 9,
    ip_address: "19.182.162.193",
    job_title: "Assistant Manager",
    key: 9,
    last_name: "Gosselin",
    shirt_size: "3XL",
  },
  {
    app_name: "Tresom",
    app_version: "0.6.8",
    buzzword: "productivity",
    company_name: "Torp, Altenwerth and Runolfsson",
    credit_card_number: 374622594660937,
    currency: "Shilling",
    currency_code: "SOS",
    department: "Sales",
    domain_name: "ow.ly",
    email: "jbrushneen9@fotki.com",
    first_name: "Joceline",
    gender: "Female",
    guid: "d3af8777-7341-4b52-a93a-6204e5a153bb",
    id: 10,
    ip_address: "142.44.166.35",
    job_title: "Account Executive",
    key: 10,
    last_name: "Brushneen",
    shirt_size: "XS",
  },
  {
    app_name: "Y-find",
    app_version: "9.5.8",
    buzzword: "knowledge base",
    company_name: "Thiel Group",
    credit_card_number: 3580273946709412,
    currency: "Peso",
    currency_code: "PHP",
    department: "Business Development",
    domain_name: "zdnet.com",
    email: "wmarskella@mayoclinic.com",
    first_name: "William",
    gender: "Female",
    guid: "b67cab6d-09e2-4488-ab09-21b0b4602db2",
    id: 11,
    ip_address: "81.128.177.11",
    job_title: "Nurse",
    key: 11,
    last_name: "Marskell",
    shirt_size: "L",
  },
  {
    app_name: "Flowdesk",
    app_version: 0.39,
    buzzword: "intranet",
    company_name: "Medhurst-Rau",
    credit_card_number: 3544976316054269,
    currency: "Rupiah",
    currency_code: "IDR",
    department: "Human Resources",
    domain_name: "google.com.au",
    email: "ppaysb@salon.com",
    first_name: "Petronille",
    gender: "Polygender",
    guid: "2447d583-3aaf-4041-ae8d-c18be28e7695",
    id: 12,
    ip_address: "243.51.208.133",
    job_title: "VP Marketing",
    key: 12,
    last_name: "Pays",
    shirt_size: "3XL",
  },
  {
    app_name: "Subin",
    app_version: 5,
    buzzword: "core",
    company_name: "Hackett and Sons",
    credit_card_number: 3529415443141201,
    currency: "Baht",
    currency_code: "THB",
    department: "Legal",
    domain_name: "arstechnica.com",
    email: "dstreetleyc@blogs.com",
    first_name: "Donielle",
    gender: "Bigender",
    guid: "4194a9ee-8df5-440b-b4b6-f0916cb458e5",
    id: 13,
    ip_address: "131.226.233.206",
    job_title: "Web Designer IV",
    key: 13,
    last_name: "Streetley",
    shirt_size: "L",
  },
  {
    app_name: "Duobam",
    app_version: 0.18,
    buzzword: "Grass-roots",
    company_name: "Grant and Sons",
    credit_card_number: 3532022554787874,
    currency: "Euro",
    currency_code: "EUR",
    department: "Training",
    domain_name: "nymag.com",
    email: "kbauckhamd@gmpg.org",
    first_name: "Kirby",
    gender: "Agender",
    guid: "e232b2d3-d970-45ae-9a82-7141581f0e02",
    id: 14,
    ip_address: "76.55.175.39",
    job_title: "Programmer Analyst I",
    key: 14,
    last_name: "Bauckham",
    shirt_size: "XL",
  },
  {
    app_name: "Gembucket",
    app_version: 8.74,
    buzzword: "Polarised",
    company_name: "O'Connell, Mueller and Hintz",
    credit_card_number: 676374294410437600,
    currency: "Peso",
    currency_code: "ARS",
    department: "Engineering",
    domain_name: "gravatar.com",
    email: "rmcmorrane@si.edu",
    first_name: "Rosella",
    gender: "Bigender",
    guid: "062102bc-394c-45eb-bad1-616d3d29b3f2",
    id: 15,
    ip_address: "38.195.52.98",
    job_title: "Administrative Officer",
    key: 15,
    last_name: "McMorran",
    shirt_size: "2XL",
  },
  {
    app_name: "Zontrax",
    app_version: 0.66,
    buzzword: "Self-enabling",
    company_name: "Hintz LLC",
    credit_card_number: 4041379016969579,
    currency: "Euro",
    currency_code: "EUR",
    department: "Research and Development",
    domain_name: "surveymonkey.com",
    email: "dlettyf@wikimedia.org",
    first_name: "Donaugh",
    gender: "Female",
    guid: "ca7f23bc-64e1-4740-9f8a-76d1a8ba82a4",
    id: 16,
    ip_address: "103.30.154.240",
    job_title: "Tax Accountant",
    key: 16,
    last_name: "Letty",
    shirt_size: "M",
  },
  {
    app_name: "Zoolab",
    app_version: 3.61,
    buzzword: "radical",
    company_name: "Wehner Inc",
    credit_card_number: 5464311981590119,
    currency: "Hryvnia",
    currency_code: "UAH",
    department: "Research and Development",
    domain_name: "sitemeter.com",
    email: "lduforeg@rediff.com",
    first_name: "Luis",
    gender: "Female",
    guid: "6865d197-4b4e-499a-a05a-5e12293b4828",
    id: 17,
    ip_address: "73.192.236.39",
    job_title: "Social Worker",
    key: 17,
    last_name: "Dufore",
    shirt_size: "2XL",
  },
  {
    app_name: "Zoolab",
    app_version: 0.68,
    buzzword: "Upgradable",
    company_name: "Bosco-Rodriguez",
    credit_card_number: 4026584466448789,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Accounting",
    domain_name: "intel.com",
    email: "dtantih@quantcast.com",
    first_name: "Delly",
    gender: "Genderfluid",
    guid: "83c939de-ede2-4e8d-9399-baef9aa79a86",
    id: 18,
    ip_address: "19.34.47.1",
    job_title: "Clinical Specialist",
    key: 18,
    last_name: "Tanti",
    shirt_size: "M",
  },
  {
    app_name: "Tresom",
    app_version: "0.1.6",
    buzzword: "executive",
    company_name: "Hodkiewicz-Barton",
    credit_card_number: 3582508580807750,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Marketing",
    domain_name: "istockphoto.com",
    email: "meakini@163.com",
    first_name: "Margarete",
    gender: "Agender",
    guid: "f99f09f4-708d-4526-b818-9da6a7ef4ac2",
    id: 19,
    ip_address: "203.140.170.240",
    job_title: "Paralegal",
    key: 19,
    last_name: "Eakin",
    shirt_size: "L",
  },
  {
    app_name: "Biodex",
    app_version: "5.2.2",
    buzzword: "Ergonomic",
    company_name: "Breitenberg, Wiza and Lowe",
    credit_card_number: 3572790732285737,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Marketing",
    domain_name: "goodreads.com",
    email: "agillhespyj@php.net",
    first_name: "Agneta",
    gender: "Bigender",
    guid: "ee25a901-aa59-4142-bc36-9eb49b90268e",
    id: 20,
    ip_address: "178.218.21.66",
    job_title: "Technical Writer",
    key: 20,
    last_name: "Gillhespy",
    shirt_size: "XS",
  },
  {
    app_name: "Bytecard",
    app_version: 0.16,
    buzzword: "fault-tolerant",
    company_name: "Baumbach Inc",
    credit_card_number: 5602221156261995,
    currency: "Euro",
    currency_code: "EUR",
    department: "Engineering",
    domain_name: "cnbc.com",
    email: "orasherk@behance.net",
    first_name: "Osbert",
    gender: "Genderqueer",
    guid: "95a4a128-8fca-4db4-8969-43ce26150abe",
    id: 21,
    ip_address: "241.51.123.49",
    job_title: "Media Manager I",
    key: 21,
    last_name: "Rasher",
    shirt_size: "XS",
  },
  {
    app_name: "Pannier",
    app_version: 4.33,
    buzzword: "functionalities",
    company_name: "Christiansen, Littel and Hane",
    credit_card_number: 3558670031398837,
    currency: "Rupiah",
    currency_code: "IDR",
    department: "Research and Development",
    domain_name: "tiny.cc",
    email: "jvedeniktovl@fda.gov",
    first_name: "Janeva",
    gender: "Polygender",
    guid: "6c620e0b-8f13-447b-87d9-980ef714e5d9",
    id: 22,
    ip_address: "218.238.9.122",
    job_title: "Office Assistant III",
    key: 22,
    last_name: "Vedeniktov",
    shirt_size: "M",
  },
  {
    app_name: "Redhold",
    app_version: "0.5.4",
    buzzword: "internet solution",
    company_name: "Larkin, Streich and Lowe",
    credit_card_number: 6334279038674233000,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Training",
    domain_name: "ibm.com",
    email: "bskacelm@omniture.com",
    first_name: "Berkeley",
    gender: "Agender",
    guid: "8866454e-7d6e-4238-acfc-bf4e7a51c7a9",
    id: 23,
    ip_address: "60.45.85.209",
    job_title: "General Manager",
    key: 23,
    last_name: "Skacel",
    shirt_size: "XL",
  },
  {
    app_name: "Tampflex",
    app_version: 0.8,
    buzzword: "flexibility",
    company_name: "Lang-Effertz",
    credit_card_number: 5602224025594026,
    currency: "Afghani",
    currency_code: "AFN",
    department: "Business Development",
    domain_name: "hatena.ne.jp",
    email: "lmelluishn@squarespace.com",
    first_name: "Leona",
    gender: "Genderfluid",
    guid: "2f4d7cb5-b4e7-4e86-add9-19cd821cec48",
    id: 24,
    ip_address: "194.76.65.241",
    job_title: "Recruiter",
    key: 24,
    last_name: "Melluish",
    shirt_size: "2XL",
  },
  {
    app_name: "Ronstring",
    app_version: 5.2,
    buzzword: "content-based",
    company_name: "Stokes-Rath",
    credit_card_number: 3559779202186571,
    currency: "Yuan Renminbi",
    currency_code: "CNY",
    department: "Human Resources",
    domain_name: "liveinternet.ru",
    email: "afieldstoneo@ning.com",
    first_name: "Ashbey",
    gender: "Non-binary",
    guid: "af1203f8-2f00-4097-a41c-1f269b99bdd6",
    id: 25,
    ip_address: "47.209.60.4",
    job_title: "Analog Circuit Design manager",
    key: 25,
    last_name: "Fieldstone",
    shirt_size: "XS",
  },
];
