#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/helpers/lint_staged.sh"
. "$(dirname "$0")/helpers/prevent_pushing_to_master.sh"
. "$(dirname "$0")/helpers/prevent_conflict_markers.sh"

prevent_pushing_to_master
prevent_conflict_markers
lint_staged_files
